/*
|--------------------------------------------------------------------------
| DIGESTEX Industry Blueprint Factory™
|--------------------------------------------------------------------------
|
| Resolves the appropriate Industry Blueprint based on the
| Business Classification generated by BusinessClassificationService.
|
| Flow
|
| Business Identity
|        ↓
| BusinessClassificationService
|        ↓
| framework.capability_profile
|        ↓
| IndustryBlueprintRegistry™
|        ↓
| Industry Blueprint
|
|--------------------------------------------------------------------------
*/

import IndustryBlueprintRegistry from "./IndustryBlueprintRegistry";

/*
|--------------------------------------------------------------------------
| Factory
|--------------------------------------------------------------------------
*/

export default function IndustryBlueprintFactory(business = {}) {
    /*
    |--------------------------------------------------------------------------
    | Framework
    |--------------------------------------------------------------------------
    */

    const framework = business?.framework ?? {};

    /*
    |--------------------------------------------------------------------------
    | Capability Profile
    |--------------------------------------------------------------------------
    */

    const profile =
        framework.capability_profile ??
        business?.capability_profile ??
        "manufacturer";

    /*
    |--------------------------------------------------------------------------
    | Blueprint
    |--------------------------------------------------------------------------
    */

    return (
        IndustryBlueprintRegistry[profile] ??
        IndustryBlueprintRegistry.manufacturer
    );
}
