/*
|--------------------------------------------------------------------------
| DIGESTEX Intelligence Card™
|--------------------------------------------------------------------------
|
| Displays insights generated by the DIGESTEX Decision Engine.
|
| This component will evolve into AI Recommendation™,
| Buyer Readiness™, and Smart Business Matching™.
|
|--------------------------------------------------------------------------
*/

import { Brain, Sparkles, ArrowRight, CheckCircle2 } from "lucide-react";

export default function IntelligenceCard({ classification = {} }) {
    const {
        primaryCategory = "general",
        capabilityProfile = "general",
        manufacturingProfile = "general",
        modules = [],
    } = classification;

    const ready = primaryCategory !== "general";

    return (
        <div className="rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-50 via-white to-sky-50 p-6 shadow-sm">
            {/* Header */}

            <div className="flex items-center gap-3">
                <div className="rounded-xl bg-indigo-100 p-2">
                    <Brain className="h-6 w-6 text-indigo-600" />
                </div>

                <div>
                    <div className="text-sm font-semibold text-indigo-600">
                        DIGESTEX Intelligence™
                    </div>

                    <div className="text-xl font-black">Decision Engine</div>
                </div>
            </div>

            {/* Waiting */}

            {!ready && (
                <div className="mt-6 rounded-xl bg-white p-5">
                    <div className="flex items-center gap-2">
                        <Sparkles className="h-5 w-5 text-slate-400" />

                        <span className="font-semibold">
                            Waiting for Analysis
                        </span>
                    </div>

                    <p className="mt-3 text-sm leading-6 text-slate-600">
                        Select one or more business activities. DIGESTEX
                        Decision Engine™ will automatically determine your
                        Business Framework.
                    </p>
                </div>
            )}

            {/* Ready */}

            {ready && (
                <>
                    <div className="mt-6 rounded-xl bg-white p-5">
                        <div className="flex items-center gap-2">
                            <CheckCircle2 className="h-5 w-5 text-emerald-600" />

                            <span className="font-bold text-emerald-700">
                                Business Successfully Classified
                            </span>
                        </div>

                        <p className="mt-3 text-sm leading-6 text-slate-600">
                            DIGESTEX has identified the most suitable business
                            framework based on your selected activities.
                        </p>
                    </div>

                    {/* Insights */}

                    <div className="mt-5 space-y-3">
                        <InsightRow
                            title="Business Category"
                            value={format(primaryCategory)}
                        />

                        <InsightRow
                            title="Capability Profile"
                            value={format(capabilityProfile)}
                        />

                        <InsightRow
                            title="Manufacturing Profile"
                            value={format(manufacturingProfile)}
                        />

                        <InsightRow
                            title="Activated Modules"
                            value={`${modules.length} Module${modules.length === 1 ? "" : "s"}`}
                        />
                    </div>

                    {/* Next */}

                    <div className="mt-6 rounded-xl border border-indigo-100 bg-indigo-50 p-4">
                        <div className="flex items-center justify-between">
                            <div>
                                <div className="font-semibold text-indigo-700">
                                    Next Step
                                </div>

                                <div className="mt-1 text-sm text-slate-600">
                                    Capability Profile™
                                </div>
                            </div>

                            <ArrowRight className="h-5 w-5 text-indigo-600" />
                        </div>
                    </div>
                </>
            )}
        </div>
    );
}

/*
|--------------------------------------------------------------------------
| Insight Row
|--------------------------------------------------------------------------
*/

function InsightRow({ title, value }) {
    return (
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3">
            <span className="text-sm text-slate-500">{title}</span>

            <span className="font-semibold">{value}</span>
        </div>
    );
}

/*
|--------------------------------------------------------------------------
| Helpers
|--------------------------------------------------------------------------
*/

function format(value) {
    if (!value) {
        return "-";
    }

    return value
        .replaceAll("_", " ")
        .replace(/\b\w/g, (char) => char.toUpperCase());
}
