/*
|--------------------------------------------------------------------------
| DIGESTEX Live Classification™
|--------------------------------------------------------------------------
|
| Displays the live result generated by the Business
| Decision Engine while the user is selecting business
| activities.
|
| This component is presentation only.
|
|--------------------------------------------------------------------------
*/

import {
    Brain,
    Factory,
    Boxes,
    Layers3,
    Network,
    Workflow,
    CheckCircle2,
} from "lucide-react";

import SummaryRow from "@/Components/Onboarding/Capability/Summary/SummaryRow";

export default function LiveClassificationCard({ classification = {} }) {
    const {
        primaryCategory,
        industryType,
        valueChain,
        primaryBusiness,
        capabilityProfile,
        manufacturingProfile,
        modules = [],
    } = classification;

    const hasSelection = primaryCategory && primaryCategory !== "general";

    return (
        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
            {/* ------------------------------------------------------------ */}
            {/* Header */}
            {/* ------------------------------------------------------------ */}

            <div className="flex items-center gap-3">
                <Brain className="h-7 w-7 text-indigo-600" />

                <div>
                    <h2 className="text-xl font-black">
                        Business Intelligence™
                    </h2>

                    <p className="text-sm text-slate-500">
                        Live Classification Preview
                    </p>
                </div>
            </div>

            {/* ------------------------------------------------------------ */}
            {/* Waiting */}
            {/* ------------------------------------------------------------ */}

            {!hasSelection && (
                <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6">
                    <div className="text-center">
                        <Brain className="mx-auto h-10 w-10 text-slate-400" />

                        <div className="mt-4 text-lg font-bold text-slate-700">
                            Waiting for Business Selection
                        </div>

                        <p className="mt-2 text-sm leading-6 text-slate-500">
                            Select one or more business activities to let
                            DIGESTEX classify your company automatically.
                        </p>
                    </div>
                </div>
            )}

            {/* ------------------------------------------------------------ */}
            {/* Classification */}
            {/* ------------------------------------------------------------ */}

            {hasSelection && (
                <>
                    <div className="mt-7 space-y-1">
                        <SummaryRow
                            icon={Factory}
                            label="Primary Category"
                            value={format(primaryCategory)}
                        />

                        <SummaryRow
                            icon={Network}
                            label="Industry Type"
                            value={format(industryType)}
                        />

                        <SummaryRow
                            icon={Workflow}
                            label="Value Chain"
                            value={format(valueChain)}
                        />

                        <SummaryRow
                            icon={Layers3}
                            label="Primary Business"
                            value={format(primaryBusiness)}
                        />

                        <SummaryRow
                            icon={Boxes}
                            label="Capability Framework"
                            value={format(capabilityProfile)}
                        />

                        <SummaryRow
                            icon={Factory}
                            label="Manufacturing Framework"
                            value={format(manufacturingProfile)}
                        />
                    </div>

                    {/* ---------------------------------------------------- */}
                    {/* Modules */}
                    {/* ---------------------------------------------------- */}

                    <div className="mt-8 rounded-2xl bg-slate-50 p-5">
                        <div className="font-bold text-slate-700">
                            Modules Ready
                        </div>

                        <div className="mt-4 flex flex-wrap gap-2">
                            {modules.map((module) => (
                                <span
                                    key={module}
                                    className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700"
                                >
                                    {format(module)}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* ---------------------------------------------------- */}
                    {/* Intelligence */}
                    {/* ---------------------------------------------------- */}

                    <div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50 p-5">
                        <div className="flex items-center gap-2">
                            <CheckCircle2 className="h-5 w-5 text-emerald-600" />

                            <span className="font-bold text-emerald-700">
                                DIGESTEX Intelligence™
                            </span>
                        </div>

                        <p className="mt-3 text-sm leading-6 text-slate-600">
                            Your business has been classified successfully. Step
                            3 will automatically display the capability profile
                            that best matches your business model.
                        </p>
                    </div>
                </>
            )}
        </div>
    );
}

/*
|--------------------------------------------------------------------------
| Helpers
|--------------------------------------------------------------------------
*/

function format(value) {
    if (!value) {
        return "-";
    }

    return value
        .replaceAll("_", " ")
        .replace(/\b\w/g, (char) => char.toUpperCase());
}
