/*
|--------------------------------------------------------------------------
| DIGESTEX Capability Blueprint Registry™
|--------------------------------------------------------------------------
|
| Single Source of Truth for every Capability Profile.
|
| This registry maps the capability profile generated by
| BusinessClassificationService to a complete UI blueprint.
|
|--------------------------------------------------------------------------
*/

import { Factory, FlaskConical, ShoppingBag, Wrench } from "lucide-react";

/*
|--------------------------------------------------------------------------
| Capability Components
|--------------------------------------------------------------------------
*/

import ManufacturerCapability from "./Manufacturer/ManufacturerCapability";
import QualityCapability from "./Quality/QualityCapability";
import CommercialCapability from "./Commercial/CommercialCapability";
import SupportingCapability from "./Supporting/SupportingCapability";

/*
|--------------------------------------------------------------------------
| Blueprint Registry
|--------------------------------------------------------------------------
*/

const CapabilityBlueprintRegistry = {
    /*
    |--------------------------------------------------------------------------
    | Manufacturer
    |--------------------------------------------------------------------------
    */

    manufacturer: {
        title: "Manufacturer Capability™",

        description:
            "Configure your manufacturing capability, production capacity and operational readiness.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_fiber: {
        title: "Fiber Producer Capability™",

        description: "Configure fiber manufacturing capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_spinner: {
        title: "Spinner Capability™",

        description: "Configure spinning capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_weaving: {
        title: "Weaving Capability™",

        description: "Configure weaving capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_knitting: {
        title: "Knitting Capability™",

        description: "Configure knitting capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_dyeing: {
        title: "Dyeing & Finishing Capability™",

        description: "Configure dyeing and finishing capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_printing: {
        title: "Printing Capability™",

        description: "Configure textile printing capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    manufacturer_garment: {
        title: "Garment Manufacturing Capability™",

        description: "Configure garment manufacturing capability.",

        component: ManufacturerCapability,

        icon: Factory,

        color: "blue",

        progress: 0,

        sections: [
            "factory_information",

            "production",

            "machinery",

            "capacity",

            "commercial",

            "export",

            "certification",

            "sustainability",

            "flexibility",
        ],
    },

    /*
    |--------------------------------------------------------------------------
    | Quality Infrastructure
    |--------------------------------------------------------------------------
    */

    quality: {
        title: "Quality Infrastructure Capability™",

        description: "Configure quality assurance and laboratory capability.",

        component: QualityCapability,

        icon: FlaskConical,

        color: "emerald",

        progress: 0,

        sections: ["laboratory", "testing", "accreditation", "certification"],
    },

    quality_laboratory: {
        title: "Laboratory Capability™",

        description: "Configure testing laboratory capability.",

        component: QualityCapability,

        icon: FlaskConical,

        color: "emerald",

        progress: 0,

        sections: ["laboratory", "testing", "accreditation", "certification"],
    },

    quality_certification: {
        title: "Certification Body Capability™",

        description: "Configure certification body capability.",

        component: QualityCapability,

        icon: FlaskConical,

        color: "emerald",

        progress: 0,

        sections: ["laboratory", "testing", "accreditation", "certification"],
    },

    /*
    |--------------------------------------------------------------------------
    | Commercial
    |--------------------------------------------------------------------------
    */

    commercial: {
        title: "Commercial Capability™",

        description: "Configure commercial capability.",

        component: CommercialCapability,

        icon: ShoppingBag,

        color: "amber",

        progress: 0,

        sections: ["buyer", "market", "export"],
    },

    commercial_trader: {
        title: "Trading Company Capability™",

        description: "Configure trading capability.",

        component: CommercialCapability,

        icon: ShoppingBag,

        color: "amber",

        progress: 0,

        sections: ["buyer", "market", "export"],
    },

    commercial_brand: {
        title: "Brand Owner Capability™",

        description: "Configure brand capability.",

        component: CommercialCapability,

        icon: ShoppingBag,

        color: "amber",

        progress: 0,

        sections: ["buyer", "market", "export"],
    },

    commercial_buying_office: {
        title: "Buying Office Capability™",

        description: "Configure buying office capability.",

        component: CommercialCapability,

        icon: ShoppingBag,

        color: "amber",

        progress: 0,

        sections: ["buyer", "market", "export"],
    },

    /*
    |--------------------------------------------------------------------------
    | Supporting Industry
    |--------------------------------------------------------------------------
    */

    supporting: {
        title: "Supporting Industry Capability™",

        description: "Configure supporting industry capability.",

        component: SupportingCapability,

        icon: Wrench,

        color: "purple",

        progress: 0,

        sections: ["product", "distribution", "technical_support"],
    },

    supporting_machinery: {
        title: "Machinery Supplier Capability™",

        description: "Configure machinery supplier capability.",

        component: SupportingCapability,

        icon: Wrench,

        color: "purple",

        progress: 0,

        sections: ["product", "distribution", "technical_support"],
    },

    supporting_accessories: {
        title: "Accessories Supplier Capability™",

        description: "Configure accessories supplier capability.",

        component: SupportingCapability,

        icon: Wrench,

        color: "purple",

        progress: 0,

        sections: ["product", "distribution", "technical_support"],
    },

    supporting_chemical: {
        title: "Chemical Supplier Capability™",

        description: "Configure chemical supplier capability.",

        component: SupportingCapability,

        icon: Wrench,

        color: "purple",

        progress: 0,

        sections: ["product", "distribution", "technical_support"],
    },
};

export default CapabilityBlueprintRegistry;
