/*
|--------------------------------------------------------------------------
| DIGESTEX Capability Registry™
|--------------------------------------------------------------------------
|
| Maps Capability Profiles generated by
| BusinessClassificationService to their
| corresponding Capability Components.
|
| Flow
|
| Business Identity
|        ↓
| BusinessClassificationService
|        ↓
| framework.capability_profile
|        ↓
| CapabilityRegistry
|        ↓
| CapabilityFactory
|        ↓
| CapabilityRouter
|
|--------------------------------------------------------------------------
*/

import ManufacturerCapability from "./Manufacturer/ManufacturerCapability";
import QualityCapability from "./Quality/QualityCapability";
import SupportingCapability from "./Supporting/SupportingCapability";
import CommercialCapability from "./Commercial/CommercialCapability";

/*
|--------------------------------------------------------------------------
| Capability Registry
|--------------------------------------------------------------------------
*/

export const CapabilityRegistry = {
    /*
    |--------------------------------------------------------------------------
    | Manufacturer
    |--------------------------------------------------------------------------
    */

    manufacturer: ManufacturerCapability,

    manufacturer_fiber: ManufacturerCapability,

    manufacturer_spinner: ManufacturerCapability,

    manufacturer_weaving: ManufacturerCapability,

    manufacturer_knitting: ManufacturerCapability,

    manufacturer_dyeing: ManufacturerCapability,

    manufacturer_printing: ManufacturerCapability,

    manufacturer_garment: ManufacturerCapability,

    /*
    |--------------------------------------------------------------------------
    | Quality Infrastructure
    |--------------------------------------------------------------------------
    */

    quality: QualityCapability,

    quality_laboratory: QualityCapability,

    quality_certification: QualityCapability,

    /*
    |--------------------------------------------------------------------------
    | Supporting Industry
    |--------------------------------------------------------------------------
    */

    supporting: SupportingCapability,

    supporting_machinery: SupportingCapability,

    supporting_accessories: SupportingCapability,

    supporting_chemical: SupportingCapability,

    /*
    |--------------------------------------------------------------------------
    | Commercial
    |--------------------------------------------------------------------------
    */

    commercial: CommercialCapability,

    commercial_trader: CommercialCapability,

    commercial_brand: CommercialCapability,

    commercial_buying_office: CommercialCapability,
};

export default CapabilityRegistry;
