/*
|--------------------------------------------------------------------------
| DIGESTEX Capability Factory™
|--------------------------------------------------------------------------
|
| Resolves the appropriate Capability Blueprint based on the
| Framework generated by BusinessClassificationService.
|
| Flow
|
| BusinessClassificationService
|          │
|          ▼
| framework.capability_profile
|          │
|          ▼
| CapabilityBlueprintRegistry
|          │
|          ▼
| Blueprint
|
|--------------------------------------------------------------------------
*/

import CapabilityBlueprintRegistry from "./CapabilityBlueprintRegistry";

/*
|--------------------------------------------------------------------------
| Capability Factory
|--------------------------------------------------------------------------
*/

export default function CapabilityFactory(framework = {}) {
    /*
    |--------------------------------------------------------------------------
    | Resolve Capability Profile
    |--------------------------------------------------------------------------
    */

    const profile = framework?.capability_profile ?? "manufacturer";

    /*
    |--------------------------------------------------------------------------
    | Resolve Blueprint
    |--------------------------------------------------------------------------
    */

    const blueprint =
        CapabilityBlueprintRegistry[profile] ??
        CapabilityBlueprintRegistry.manufacturer;

    /*
    |--------------------------------------------------------------------------
    | Return Blueprint
    |--------------------------------------------------------------------------
    */

    return {
        profile,

        ...blueprint,
    };
}
