<?php

declare(strict_types=1);

namespace App\Services\MasterData\Generator;

use Illuminate\Support\Facades\File;

/**
 * ==========================================================================
 * DIGESTEX CORE
 * ==========================================================================
 * Schema Exporter
 * ==========================================================================
 *
 * Exports generated SchemaDefinition objects into
 * schemas.generated.php
 *
 * Responsibilities
 * ----------------
 * - Format schema output
 * - Write generated schema
 * - Never overwrite schemas.php
 *
 * Used by:
 *
 * MasterDataSchemaGenerator
 *
 * ==========================================================================
 */
class SchemaExporter
{
    /**
     * Output filename.
     */
    protected string $filename = 'schemas.generated.php';

    /**
     * =========================================================================
     * Export
     * =========================================================================
     *
     * @param array<string,SchemaDefinition> $definitions
     */
    public function export(
        array $definitions,
        ?string $directory = null
    ): string
    {
        $directory ??= config_path('masterdata');

        if (! File::exists($directory)) {
            File::makeDirectory(
                $directory,
                0755,
                true
            );
        }

        ksort($definitions);

        $schema = [];

        foreach ($definitions as $file => $definition) {

            $schema[$file] = $definition->toArray();

        }

        $content = $this->buildPhpFile(
            $schema
        );

        $path = $directory
            . DIRECTORY_SEPARATOR
            . $this->filename;

        File::put(
            $path,
            $content
        );

        return $path;
    }

    /**
     * =========================================================================
     * Build PHP File
     * =========================================================================
     *
     * @param array<string,mixed> $schema
     */
    protected function buildPhpFile(
        array $schema
    ): string
    {
        $export = var_export(
            $schema,
            true
        );

        /*
        |--------------------------------------------------------------------------
        | Convert array() to []
        |--------------------------------------------------------------------------
        */

        $export = preg_replace(
            [
                "/array \\(/",
                "/^([ ]*)\\)(,?)$/m",
            ],
            [
                "[",
                "$1]$2",
            ],
            $export
        );

        return <<<PHP
<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| -------------------------------------------------------------------------
| THIS FILE IS AUTO-GENERATED
|--------------------------------------------------------------------------
|
| Generated by:
|
| php artisan digestex:generate-schema
|
| DO NOT EDIT THIS FILE MANUALLY.
|
| -------------------------------------------------------------------------
*/

return {$export};

PHP;
    }

    /**
     * =========================================================================
     * Output Filename
     * =========================================================================
     */
    public function filename(): string
    {
        return $this->filename;
    }

    /**
     * =========================================================================
     * Output Path
     * =========================================================================
     */
    public function outputPath(
        ?string $directory = null
    ): string
    {
        $directory ??= config_path(
            'masterdata'
        );

        return $directory
            . DIRECTORY_SEPARATOR
            . $this->filename;
    }
}