<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| -------------------------------------------------------------------------
| THIS FILE IS AUTO-GENERATED
|--------------------------------------------------------------------------
|
| Generated by:
|
| php artisan digestex:generate-schema
|
| DO NOT EDIT THIS FILE MANUALLY.
|
| -------------------------------------------------------------------------
*/

return [
  'Business/business_ecosystems.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Business/business_roles.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'category',
      2 => 'color',
      3 => 'description',
      4 => 'downstream',
      5 => 'icon',
      6 => 'priority',
      7 => 'sustainability',
      8 => 'technologies',
      9 => 'upstream',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'category' => 'string',
      'color' => 'string',
      'description' => 'string',
      'downstream' => 'array',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
      'sustainability' => 'array',
      'technologies' => 'array',
      'upstream' => 'array',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Business/buyer_segments.php' => 
  [
    'identity' => NULL,
    'type' => 'knowledge_node',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'category',
      1 => 'description',
      2 => 'icon',
      3 => 'preferred_sustainability',
      4 => 'priority',
      5 => 'required_certifications',
      6 => 'typical_markets',
      7 => 'typical_products',
    ],
    'types' => 
    [
      'category' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'preferred_sustainability' => 'array',
      'priority' => 'integer',
      'required_certifications' => 'array',
      'typical_markets' => 'array',
      'typical_products' => 'array',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
      'required_certifications' => 
      [
        'field' => 'required_certifications',
        'target' => 'certifications',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "required_certifications" to "certifications" (certifications).',
      ],
      'typical_markets' => 
      [
        'field' => 'typical_markets',
        'target' => 'certification_markets',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "typical_markets" to "certification_markets" (certification_markets).',
      ],
      'typical_products' => 
      [
        'field' => 'typical_products',
        'target' => 'product_categories',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "typical_products" to "products" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Business/supplier_segments.php' => 
  [
    'identity' => NULL,
    'type' => 'knowledge_node',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'category',
      1 => 'common_business_roles',
      2 => 'common_buyer_segments',
      3 => 'common_certifications',
      4 => 'common_sustainability',
      5 => 'description',
      6 => 'icon',
      7 => 'priority',
      8 => 'typical_markets',
      9 => 'typical_products',
    ],
    'types' => 
    [
      'category' => 'string',
      'common_business_roles' => 'array',
      'common_buyer_segments' => 'array',
      'common_certifications' => 'array',
      'common_sustainability' => 'array',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
      'typical_markets' => 'array',
      'typical_products' => 'array',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
      'common_business_roles' => 
      [
        'field' => 'common_business_roles',
        'target' => 'business_roles',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "common_business_roles" to "business_roles" (business_roles).',
      ],
      'common_buyer_segments' => 
      [
        'field' => 'common_buyer_segments',
        'target' => 'buyer_segments',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "common_buyer_segments" to "buyer_segments" (buyer_segments).',
      ],
      'common_certifications' => 
      [
        'field' => 'common_certifications',
        'target' => 'certifications',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "common_certifications" to "certifications" (certifications).',
      ],
      'typical_markets' => 
      [
        'field' => 'typical_markets',
        'target' => 'certification_markets',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "typical_markets" to "certification_markets" (certification_markets).',
      ],
      'typical_products' => 
      [
        'field' => 'typical_products',
        'target' => 'product_categories',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "typical_products" to "products" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Certification/certification_bodies.php' => 
  [
    'identity' => NULL,
    'type' => 'knowledge_node',
    'required' => 
    [
      0 => 'id',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'category',
      2 => 'country',
      3 => 'description',
      4 => 'name',
      5 => 'recognized_globally',
      6 => 'short_name',
      7 => 'website',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'category' => 'string',
      'country' => 'string',
      'description' => 'string',
      'id' => 'string',
      'name' => 'string',
      'recognized_globally' => 'boolean',
      'short_name' => 'string',
      'website' => 'string',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Certification/certification_categories.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Certification/certification_markets.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'description',
      2 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'description' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Certification/certification_scopes.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'description',
      2 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'description' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Certification/certifications.php' => 
  [
    'identity' => NULL,
    'type' => 'knowledge_node',
    'required' => 
    [
      0 => 'id',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'category',
      2 => 'description',
      3 => 'full_name',
      4 => 'issuer',
      5 => 'name',
      6 => 'recognized_markets',
      7 => 'renewal_years',
      8 => 'scope',
      9 => 'supports_esg',
      10 => 'supports_quality',
      11 => 'supports_sustainability',
      12 => 'supports_traceability',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'category' => 'string',
      'description' => 'string',
      'full_name' => 'string',
      'id' => 'string',
      'issuer' => 'string',
      'name' => 'string',
      'recognized_markets' => 'array',
      'renewal_years' => 'integer',
      'scope' => 'array',
      'supports_esg' => 'boolean',
      'supports_quality' => 'boolean',
      'supports_sustainability' => 'boolean',
      'supports_traceability' => 'boolean',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
      'recognized_markets' => 
      [
        'field' => 'recognized_markets',
        'target' => 'certification_markets',
        'relation' => 'many_to_many',
        'collection' => true,
        'confidence' => 100,
        'reason' => 'Normalized "recognized_markets" to "certification_markets" (certification_markets).',
      ],
      'scope' => 
      [
        'field' => 'scope',
        'target' => 'certification_scopes',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "scope" to "certification_scopes" (certification_scopes).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Machinery/machinery_categories.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Products/product_applications.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Products/product_categories.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'Products/product_statuses.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'color',
      2 => 'description',
      3 => 'icon',
      4 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'color' => 'string',
      'description' => 'string',
      'icon' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'industry_segments.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'description',
      2 => 'ecosystem',
      3 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'description' => 'string',
      'ecosystem' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
      'ecosystem' => 
      [
        'field' => 'ecosystem',
        'target' => 'business_ecosystems',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "ecosystem" to "business_ecosystems" (business_ecosystems).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'sustainability_tags.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'category',
      2 => 'description',
      3 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'category' => 'string',
      'description' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
  'technologies.php' => 
  [
    'identity' => NULL,
    'type' => 'lookup',
    'required' => 
    [
      0 => 'id',
      1 => 'label',
    ],
    'optional' => 
    [
      0 => 'active',
      1 => 'category',
      2 => 'description',
      3 => 'priority',
    ],
    'types' => 
    [
      'active' => 'boolean',
      'category' => 'string',
      'description' => 'string',
      'id' => 'string',
      'label' => 'string',
      'priority' => 'integer',
    ],
    'references' => 
    [
      'category' => 
      [
        'field' => 'category',
        'target' => 'product_categories',
        'relation' => 'belongs_to',
        'collection' => false,
        'confidence' => 100,
        'reason' => 'Normalized "category" to "product_categories" (product_categories).',
      ],
    ],
    'validation' => 
    [
      'minimum_records' => 1,
      'allow_duplicate_id' => false,
      'allow_unknown_fields' => false,
    ],
  ],
];
