/*
|--------------------------------------------------------------------------
| DIGESTEX Capability Intelligence Card™
|--------------------------------------------------------------------------
|
| Displays the Capability Framework generated by the
| BusinessClassificationService.
|
| This card acts as the Intelligence Sidebar for Step 3.
|
|--------------------------------------------------------------------------
*/

import { Factory, Boxes, Cog, Layers3 } from "lucide-react";

import SummaryRow from "./SummaryRow";

export default function CapabilityIntelligenceCard({
    business = {},
    framework = {},
}) {
    /*
    |--------------------------------------------------------------------------
    | Resolve Data
    |--------------------------------------------------------------------------
    */

    const category = business.primary_business_category ?? "-";

    const line = business.primary_line_of_business ?? "-";

    const capability = framework.capability_profile ?? "-";

    const manufacturing = framework.manufacturing_profile ?? "-";

    const modules = framework.modules ?? [];

    return (
        <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
            {/* Header */}

            <div className="flex items-center gap-3">
                <Factory className="h-7 w-7 text-indigo-600" />

                <div>
                    <h2 className="text-xl font-black">
                        Capability Intelligence™
                    </h2>

                    <p className="text-sm text-slate-500">
                        Live Framework Preview
                    </p>
                </div>
            </div>

            {/* Summary */}

            <div className="mt-7">
                <SummaryRow
                    icon={Factory}
                    label="Business Category"
                    value={formatLabel(category)}
                />

                <SummaryRow
                    icon={Layers3}
                    label="Primary Business"
                    value={formatLabel(line)}
                />

                <SummaryRow
                    icon={Boxes}
                    label="Capability Profile"
                    value={formatLabel(capability)}
                />

                <SummaryRow
                    icon={Cog}
                    label="Manufacturing Profile"
                    value={formatLabel(manufacturing)}
                />
            </div>

            {/* Modules */}

            <div className="mt-8 rounded-2xl bg-slate-50 p-5">
                <div className="text-sm font-bold text-slate-700">
                    Modules Loaded
                </div>

                <div className="mt-4 flex flex-wrap gap-2">
                    {modules.length === 0 ? (
                        <span className="text-sm text-slate-400">
                            No modules
                        </span>
                    ) : (
                        modules.map((module) => (
                            <span
                                key={module}
                                className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700"
                            >
                                {formatLabel(module)}
                            </span>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}

/*
|--------------------------------------------------------------------------
| Helper
|--------------------------------------------------------------------------
*/

function formatLabel(value) {
    if (!value) {
        return "-";
    }

    return value
        .replaceAll("_", " ")
        .replace(/\b\w/g, (char) => char.toUpperCase());
}
