import { CalendarDays, FileBarChart2, Sparkles } from "lucide-react";

import StatusBadge from "@/Components/Common/Badges/StatusBadge";

export default function ReportHeader({
    title,

    subtitle,

    reportNumber = "TR-2026-001",

    generatedAt = "Updated Today",
}) {
    return (
        <div className="rounded-3xl border border-slate-200 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 p-10 text-white">
            <div className="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
                <div>
                    <div className="flex items-center gap-3">
                        <FileBarChart2 size={34} />

                        <div>
                            <p className="text-xs uppercase tracking-[0.35em] text-cyan-300">
                                DIGESTEX EXECUTIVE REPORT
                            </p>

                            <h1 className="mt-2 text-4xl font-black">
                                {title}
                            </h1>
                        </div>
                    </div>

                    <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">
                        {subtitle}
                    </p>
                </div>

                <div className="space-y-4">
                    <StatusBadge variant="info">
                        Official Trade Statistics
                    </StatusBadge>

                    <StatusBadge variant="success">AI Intelligence</StatusBadge>

                    <StatusBadge variant="secondary">{generatedAt}</StatusBadge>
                </div>
            </div>

            <div className="mt-10 flex flex-wrap gap-6 border-t border-slate-700 pt-6 text-sm text-slate-300">
                <div className="flex items-center gap-2">
                    <CalendarDays size={16} />
                    Report No.
                    <strong>{reportNumber}</strong>
                </div>

                <div className="flex items-center gap-2">
                    <Sparkles size={16} />
                    Generated by Digestex AI Intelligence
                </div>
            </div>
        </div>
    );
}
